### ISSUE TITLE
illegal cyclic reference with Scala 2.12.10

### ISSUE THREAD

**Issue by rgjamkhedkar** [scalikejdbc/scalikejdbc#1072] opened 2019-12-31 13:05 UTC
I am getting `scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving <refinement of scalikejdbc.QueryDSLFeature with scalikejdbc.SQLInterpolationFeature with scalikejdbc.SQLSyntaxSupportFeature>` when compiling with scala version 2.12.10. Compiling scala with 2.12.2 works fine. 
I have generated model classes with scalikejdbcGen. I tried regenerating the classes with the updated scala version, but it still produces the error. 

I am using Scalikejdbc version `3.4.0`.

Am I missing something here?

**Comment by seratch** [comment] 2020-01-13 14:09
Could you share a minimum working example that reproduces your issue?

I'm still not sure what the root cause of your issue is yet. Not only for me, if we have an easier starting point to make a dive into this issue, other people may be able to help you address the issue (or identify the cause of this if it's an issue on this library side).

**Comment by seratch** [comment] 2020-12-17 23:09
Let me close this issue after waiting for your response for more few days.

**Closed** 2021-02-20 04:55 UTC
Labels: question
