### ISSUE TITLE
Warning 'Reference to uninitialized value ec' with ConnectionPool.add()

### ISSUE THREAD

**Issue by xkrt** [scalikejdbc/scalikejdbc#568] opened 2016-09-28 07:00 UTC
Hi, I upgrade scalikejdbc lib in my project from 2.3.5 to 2.4.2 and my code want compile (since I use -Xfatal-warnings scalac flag as well known best practice).

My code:
```
ConnectionPool.add('default, db.connectionString, db.username, db.password)
```

And I get warning (error in my case):
```
Warning:(50, 21) Reference to uninitialized value ec
  ConnectionPool.add('default, db.connectionString, db.username, db.password)
```

scalikejdbc ver: 2.4.2
scala ver: 2.11.8

**Comment by seratch** [comment] 2016-09-28 07:05
fmm, maybe due to the `DEFAULT_EXECUTION_CONTEXT` is lazily initialized.

https://github.com/scalikejdbc/scalikejdbc/blob/2.4.2/scalikejdbc-core/src/main/scala/scalikejdbc/ConnectionPool.scala#L92

**Comment by xuwei-k** [comment] 2016-09-28 07:38
reproduce example


### Main.scala

```scala
import scalikejdbc._

object Main {
  ConnectionPool.add("aaa", "aaa", "aaa", "aaa")

  implicit val ec = scala.concurrent.ExecutionContext.Implicits.global
}
```

### build.sbt

```scala
scalacOptions += "-Xlint"

scalaVersion := "2.11.8"

libraryDependencies += "org.scalikejdbc" %% "scalikejdbc" % "2.4.2" // or 2.3.5
```

### warning (2.4.2 only)

```
scalikejdbc-issue-568/Main.scala:4: Reference to uninitialized value ec
[warn]   ConnectionPool.add("aaa", "aaa", "aaa", "aaa")
[warn]                     ^
[warn] one warning found
```

**Comment by xuwei-k** [comment] 2016-09-28 07:39
I think this is not scalikejdbc issue. scalac warning is right.

**Comment by seratch** [comment] 2016-09-28 08:54
@xuwei-k Thanks! 
@xkrt The warning by scalac seems to be a little bit confusing. Would you please ensure your code again?

**Comment by xkrt** [comment] 2016-09-28 11:20
@seratch sorry, what can I check. Example by @xuwei-k perfectly reproduce issue.

**Comment by seratch** [comment] 2016-09-28 11:34
@xkrt 

>Example by @xuwei-k perfectly reproduce issue.

OK. SO if the above code is like this, scalac shows no warnings.

```scala
import scalikejdbc._
object Main {
  implicit val ec = scala.concurrent.ExecutionContext.Implicits.global
  ConnectionPool.add("aaa", "aaa", "aaa", "aaa")
}
```
As @xuwei-k mentioned, this is not an issue on scalikejdbc library side. Check your code.

**Comment by xkrt** [comment] 2016-09-28 11:41
@xuwei-k yes, I can add
```
implicit val ec = scala.concurrent.ExecutionContext.Implicits.global
```
to my code and it will compile without warnings.
My point was in that I update lib version and got new warning (error with my scalac flags).

I think if users will take examples (with ConnectionPool.add(...)) from docs - them got warnings/errors and this is not good.

**Comment by seratch** [comment] 2016-09-28 11:49
@xkrt 

>I think if users will take examples (with ConnectionPool.add(...)) from docs - them got warnings/errors and this is not good.

The reason you got the warning after bumping the version is that the implicit parameter was introduced since scalikejdbc 2.4.0. https://github.com/scalikejdbc/scalikejdbc/pull/490

The following code has no warning.

```scala
import scalikejdbc._
object Main {
  //implicit val ec = scala.concurrent.ExecutionContext.Implicits.global
  ConnectionPool.add("aaa", "aaa", "aaa", "aaa")
}
```

If you simply call `ConnectionPool#add`, the warning never happens. Somewhere in your code initializes ExecutionContext lazily and it affects to the invocation of `ConnectionPool#add` method.

**Comment by xkrt** [comment] 2016-09-28 13:33
@seratch ah, I see. Thanks!

**Comment by seratch** [comment] 2016-09-28 13:34
@xkrt Would you please close this?

**Closed** 2016-09-29 12:06 UTC
Labels: question
