### ISSUE TITLE
SQLBatch factory: Factory[Int, C[Int]] implicit

### ISSUE THREAD

**Issue by safi-manar** [scalikejdbc/scalikejdbc#983] opened 2019-02-06 04:26 UTC
Hello,

I'm using `scalalikejdbc 3.3.1` and `scala 2.12.8`.

I noticed that `SQLBatch.apply()` takes implicit `factory: Factory[Int, C[Int]]`, but there are no implicits found for that factory.

When I clone this repository, I see that in `SQLSpec`, the implicit seems to be `scala.collection.compat.Factory.fromCanBuildFrom`.

Is that correct? I did not find any information in the documentation about needing to import any such libraries, so I'm wondering is there something I need to do here to make the implicit factory found?

**Comment by seratch** [comment] 2019-02-24 12:30
I am not 100% sure but I am afraid that your project uses different version of `scala-collection-compat`. Could you check the dependency out? Otherwise, sharing a working example which reproduces your situation is helpful for me. I don't have time to reproduce all users' situation. I appreciate it if you could understand it.

**Comment by ezra-quemuel** [comment] 2019-03-18 20:47
I also ran into this issue, adding `"org.scala-lang.modules" %% "scala-collection-compat" % "0.3.0"` fixed the issue. What would be the explanation for that?

**Comment by ezra-quemuel** [comment] 2019-03-19 18:24
So it looks like adding the 0.3.0 dependency actually causes problems when trying to use batching. 
Without the dependency I saw the reported warning on IntelliJ but compiled just fine

**Comment by seratch** [comment] 2019-03-21 07:42
scalikejdbc 3.3.x is compatible with scala-collection-compat 0.1.1 https://github.com/scalikejdbc/scalikejdbc/blob/3.3.3/build.sbt#L61-L67

**Comment by shrimpza** [comment] 2019-04-08 13:27
This appears to be an IntelliJ issue only. Simply applying defining a value and return type for the result of `apply()` appears to resolve IntelliJ's complaints.

For example, the example from the docs could be implemented as:

```scala
val batchResult: Seq[Int] = DB localTx { implicit session =>
  sql"insert into emp (id, name) values ({id}, {name})"
    .batchByName(Seq(Seq('id -> 1, 'name -> "Alice"), Seq('id -> 2, 'name -> "Bob")):_*)
    .apply()
}
```

`batchResult` then contains (for this example): `Seq(1, 1)`, indicating that each batch'd record affected `1` row.

**Comment by philwalk** [comment] 2019-04-10 16:55
This seems to be related a problem I'm getting.  It seems that `seratch` is correct, when I try to use any version of scala-collection-compat newer than 0.1.1, I get this runtime error:

`java.lang.ClassNotFoundException: scala.collection.compat.Factory$`

Here's my code:

```
import scalikejdbc._

object CompatScalikeTest {
  def main(args:Array[String]):Unit = {
    implicit val session = AutoSession // ad-hoc session provider
    Class.forName("org.postgresql.Driver")

    val (dbusername,dbpasswd,dbhostname) = ("postgres","","localhost")
    def url = "jdbc:postgresql://localhost/postgres"
    ConnectionPool.singleton(url,dbusername,dbpasswd)
    ConnectionPool.add('default, url,dbusername,dbpasswd)
    val settings = ConnectionPoolSettings(initialSize = 5, maxSize = 2000, connectionTimeoutMillis = 3000L, validationQuery = "select 1")
    ConnectionPool.add('default, url, dbusername, dbpasswd, settings)

    val query = SQL("select 1")
    val preserveColumnOrder = (rs:scalikejdbc.WrappedResultSet) => {
      (1 to rs.metaData.getColumnCount).foldLeft(scala.collection.immutable.ListMap[String, Any]()) { (result, i) =>
        val label = rs.metaData.getColumnLabel(i)
        Option(rs.any(label)).map { value => result + (label -> value) }.getOrElse(result)
      }
    }
    val list = query.map(
      preserveColumnOrder(_)
    ).list.apply()
    printf("%s\n",list)
  }
}
```

The exception occurs at `).list.apply()`

**Comment by philwalk** [comment] 2019-04-14 14:27
Here's my stack dump, FWIW:

```
java.lang.ClassNotFoundException: scala.collection.compat.Factory$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at scalikejdbc.DBSession.list(DBSession.scala:295)
        at scalikejdbc.DBSession.list$(DBSession.scala:294)
        at scalikejdbc.ActiveSession.list(DBSession.scala:837)
        at scalikejdbc.DBSessionWrapper.$anonfun$list$1(DBSessionWrapper.scala:52)
        at scalikejdbc.DBSessionWrapper.$anonfun$withAttributesSwitchedDBSession$1(DBSessionWrapper.scala:34)
        at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
        at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:33)
        at scalikejdbc.DBSessionWrapper.list(DBSessionWrapper.scala:52)
        at scalikejdbc.SQLToList.result(SQL.scala:931)
        at scalikejdbc.SQLToList.result$(SQL.scala:930)
        at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
        at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
        at scalikejdbc.SQLToResult.$anonfun$apply$21(SQL.scala:811)
        at scalikejdbc.DBConnection.readOnly(DBConnection.scala:211)
        at scalikejdbc.DBConnection.readOnly$(DBConnection.scala:209)
        at scalikejdbc.DB.readOnly(DB.scala:60)
        at scalikejdbc.DB$.$anonfun$readOnly$1(DB.scala:174)
        at scalikejdbc.LoanPattern.using(LoanPattern.scala:18)
        at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16)
        at scalikejdbc.DB$.using(DB.scala:139)
        at scalikejdbc.DB$.readOnly(DB.scala:173)
        at scalikejdbc.SQLToResult.apply(SQL.scala:814)
        at scalikejdbc.SQLToResult.apply$(SQL.scala:805)
        at scalikejdbc.SQLToListImpl.apply(SQL.scala:944)
        at Main$.main(compatScalikeTest.sc:35)
        at Main.main(compatScalikeTest.sc)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:106)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:132)
        at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:106)
        at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:98)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:132)
        at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:28)
        at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:27)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
        at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:35)
        at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:34)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
        at scala.tools.nsc.ScriptRunner.runCompiled(ScriptRunner.scala:180)
        at scala.tools.nsc.ScriptRunner.$anonfun$runScript$1(ScriptRunner.scala:199)
        at scala.tools.nsc.ScriptRunner.$anonfun$runScript$1$adapted(ScriptRunner.scala:199)
        at scala.tools.nsc.ScriptRunner.$anonfun$withCompiledScript$2(ScriptRunner.scala:162)
        at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:134)
        at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:210)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:77)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by philwalk** [comment] 2019-05-18 22:34
FWIW, I successfully tested a locally published clone of scalikejdbc with the following change to build.sbt:

```
-  collectionCompatVersion := "1.0.0",
+  collectionCompatVersion := "2.0.0",
```

AFAICT,  sbt tests seem to be passing.

**Comment by pedorich-n** [comment] 2019-06-17 12:10
I solved this problem by doing this

```scala
DB.autoCommit { implicit session: DBSession =>
  query.apply()(session, implicitly[Factory[Int, Seq[Int]]])
}
```
With only this import `scala.collection.compat.Factory`. I'm using ScalikeJDBC 3.3.4, Scala 2.12.8 and I didn't explicitly add the `scala-collection-compat` to my dependencies. Here is what Idea says to this `implicitly`:
![image](https://user-images.githubusercontent.com/15573098/59603374-f1e06f80-9111-11e9-8b9f-165ab113ed23.png)

**Comment by lwolters** [comment] 2019-09-13 09:21
Update scalikejdbc version: 3.4.0-RC1. Although not ideal, it works for me

**Comment by seratch** [comment] 2019-11-23 12:57
Thank you very much, all the folks in the thread. I believe ScalikeJDBC team doesn't have anything further on this issue. Allow me to close this issue.

The latest version - 3.4.0  depends on scala-collection-compat 2.1.2. If you run into similar issues in the future, check the compatibility between scalikejdbc and scala-collection-compat first.

**Closed by seratch** 2019-11-23 12:57 UTC

**Comment by l-cdc** [comment] 2022-10-05 10:00
I am still encountering this issue with scalikejdbc 4.0.0 and scala 2.13.9, in specific, IDEA reporting "No implicits found for parameter factory: compat.Factory[Int, C[Int]]". Note that the code still compiles (with SBT) and runs correctly so this might be more of an IDEA issue.

In my case, the only thing needed to avoid IDEA getting confused is using an explicit type on the `apply()` call:
`sql"INSERT INTO ...".batchByName(data: _*).apply[Seq]()`
