### ISSUE TITLE
Implicits missing

### ISSUE THREAD

**Issue by Tasselmi** [scalikejdbc/scalikejdbc#1057] opened 2019-11-10 06:21 UTC
```
spark-shell \
--jars /opt/jars/clickhouse4j-1.1.1.jar,\
/opt/jars/scalikejdbc_2.11-3.4.0.jar,\
/opt/jars/scalikejdbc-config_2.11-3.4.0.jar,\
/opt/jars/scalikejdbc-interpolation_2.11-3.4.0.jar
```

I got an unexpected error :
```
scala> import scalikejdbc._
<console>:23: error: Symbol 'type <none>.interpolation.Implicits' is missing from the classpath.
This symbol is required by 'trait scalikejdbc.SQLInterpolationFeature'.
Make sure that type Implicits is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'SQLInterpolationFeature.class' was compiled against an incompatible version of <none>.interpolation.
       import scalikejdbc._
              ^
```

**Comment by seratch** [comment] 2019-11-10 15:49
I didn't actually try to reproduce your situation but at least your command seems to be missing `scalikejdbc-core_2.11`.

**Comment by seratch** [comment] 2020-10-09 12:52
Let me close this issue but feel free to reopen it or write in as necessary.

**Closed by seratch** 2020-10-09 12:52 UTC
Labels: question
