### ISSUE TITLE
NamedAutoSession new session every time

### ISSUE THREAD

**Issue by sidhant92** [scalikejdbc/scalikejdbc#607] opened 2016-12-06 13:51 UTC
Hi im using the NamedAutoSession inside a function and calling that function directly.
The function first makes a select statement followed by insert statement. The function does this in a loop say 1000 times.
So from the db logs what i observe is its creating a new session for each read and for each write.
How can i make it use the same session for everything to save time.

**Comment by eyalroth** [comment] 2016-12-06 15:43
First off, `Named/AutoSession` simply creates a new session (whenever you create a new instance); ["auto" is quite misleading](https://groups.google.com/forum/#!topic/scalikejdbc-users-group/7KN_Tyi9I5Q).

You have to manually pass/propagate the same session object/instance between your methods (implicitly or not); however, [this will still create a new transaction for every insert, unless you change the default settings](https://groups.google.com/forum/#!searchin/scalikejdbc-users-group/eyal$20roth%7Csort:relevance/scalikejdbc-users-group/Df05SLrwo9w/Y8PG0hv-BQAJ).

**Comment by seratch** [comment] 2016-12-13 15:21
>How can i make it use the same session for everything to save time.

Simply the passing the same `DBSession` object as an implicit parameter to all the SQL executions (instead of using AutoSession) should work for you.

**Comment by eyalroth** [comment] 2017-01-22 11:35
> however, this will still create a new transaction for every insert, unless you change the default settings.

That wasn't true. I've somehow encountered that behavior but I cannot reproduce it (and after inspecting the code again it seems there's no reason for it to happen).

As @seratch mentioned, you shouldn't use `AutoSession`; it will auto-commit on every SQL execution. Instead, you have to use `ActiveSession`. Thing is, you also have to manage the transaction yourself; i.e, borrow the connection from the pool, set it to not auto-commit, and make sure to end the transaction (commit / rollback) manually.

**Comment by seratch** [comment] 2018-03-15 09:01
@sidhant92 Did my comment here help you then? If we don't have further topics to discuss here, I would like to close this issue.

**Comment by seratch** [comment] 2018-10-28 15:36
Let me close this now. Feel free to re-open this if you need to do so.

**Closed by seratch** 2018-10-28 15:36 UTC
Labels: core
